Network:
  ad_eval_epochs: 50
  batch_size: 8
  data_path: /home/minhtringuyen/ANN2SNN/dataloader/datasets/mvtec
  dataset: mvtec
  distance_lambda: 0.0125
  epochs: 200
  in_channels: 3
  input_size: 256
  k: 20
  latent_dim: 1024
  loss_func: mmd
  lr: 0.001
  mmd_type: linear
  model: ESVAE
  n_class: 1
  n_steps: 8
  sample_batch_size: 0
  sample_layer_lr_times: 10
  scheduled: true
