Network:
  ad_eval_epochs: 50
  batch_size: 8
  data_path: /home/minhtringuyen/ANN2SNN/dataloader/datasets/mvtec
  dataset: mvtec
  epochs: 200
  in_channels: 3
  input_size: 256
  k: 20
  latent_dim: 1024
  loss_func: mmd
  lr: 0.001
  model: FSVAE
  n_class: 1
  n_steps: 16
  sample_batch_size: 0
  scheduled: true
